// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPNMQBd7AqJshBpBXTmoUM_KqAMXDOwEc',
    appId: '1:660342238489:web:164725301b5608bcd5a988',
    messagingSenderId: '660342238489',
    projectId: 'fir-instal',
    authDomain: 'fir-instal.firebaseapp.com',
    storageBucket: 'fir-instal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKa4qvpg3dai9Pjq6qS71aRn1wZo5vfXI',
    appId: '1:660342238489:android:6a874db11ea35af1d5a988',
    messagingSenderId: '660342238489',
    projectId: 'fir-instal',
    storageBucket: 'fir-instal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWZShqm31e2taJU4S3rkxJ8yorTQh1fes',
    appId: '1:660342238489:ios:602276b65d732b71d5a988',
    messagingSenderId: '660342238489',
    projectId: 'fir-instal',
    storageBucket: 'fir-instal.appspot.com',
    iosBundleId: 'com.example.instaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWZShqm31e2taJU4S3rkxJ8yorTQh1fes',
    appId: '1:660342238489:ios:602276b65d732b71d5a988',
    messagingSenderId: '660342238489',
    projectId: 'fir-instal',
    storageBucket: 'fir-instal.appspot.com',
    iosBundleId: 'com.example.instaApp',
  );
}
